Stored Procedure Call: connection.prepareCall("CALL 1_DSN8.DSN8ED2(?,?,?,?,?)"), Offset: 470, Length: 56, Type: is SQL connection.prepareCall()
Stored Procedure Call: connection.prepareCall(call), Offset: 750, Length: 28, Type: is SQL connection.prepareCall()
Stored Procedure Call: connection.prepareCall("CALL 2a_DSN8.DSN8ED2(?,?,?,?,?)"), Offset: 987, Length: 57, Type: is SQL connection.prepareCall()
Stored Procedure Call: connection.prepareCall("CALL 2b_DSN8.DSN8ED2(?,?,?,?,?)"), Offset: 1168, Length: 57, Type: is SQL connection.prepareCall()
Stored Procedure Call: getCallable1("CALL 3_DSN8.DSN8ED2(?,?,?,?,?)"), Offset: 1457, Length: 46, Type: invoking method that returns a java.sql.CallableStatement
Stored Procedure Call: getCallable1("CALL 4_DSN8.DSN8ED2(?,?,?,?,?)"), Offset: 1621, Length: 46, Type: invoking method that returns a java.sql.CallableStatement
Stored Procedure Call: connection.prepareCall("CALL 5_DSN8." + name + "(?,?,?,?,?)"), Offset: 1888, Length: 61, Type: is SQL connection.prepareCall()
Stored Procedure Call: connection.prepareCall("CALL 6a_DSN8." + name + "(?,?,?,?,?)"), Offset: 2140, Length: 62, Type: is SQL connection.prepareCall()
Stored Procedure Call: connection.prepareCall("CALL 6b_DSN8." + name.trim() + "(?,?,?,?,?)"), Offset: 2257, Length: 69, Type: is SQL connection.prepareCall()
Stored Procedure Call: connection.prepareCall("CALL 6c_DSN8." + (name.length() == 0 ? "name" : name) + "(?,?,?,?,?)"), Offset: 2382, Length: 94, Type: is SQL connection.prepareCall()
Stored Procedure Call: connection.prepareCall(getCall()), Offset: 2532, Length: 33, Type: is SQL connection.prepareCall()
Stored Procedure Call: getCallable5("SP7a"), Offset: 2839, Length: 20, Type: invoking method that returns a java.sql.CallableStatement
Stored Procedure Call: getCallable5("SP7c"), Offset: 2938, Length: 20, Type: invoking method that returns a java.sql.CallableStatement
Stored Procedure Call: getCallable7(), Offset: 3083, Length: 14, Type: invoking method that returns a java.sql.CallableStatement