spring.application.name: spring-cloud-config-server
server.port: 8081
spring.cloud.config.server.git.uri: C:\Users\kdarisi\OneDrive - Deloitte (O365D)\Documents\My_Learnings\Microservices-practice\configrepo