CREATE CLASS AstBinding IF NOT EXISTS EXTENDS E;
CREATE PROPERTY AstBinding.label IF NOT EXISTS STRING (NOTNULL);
CREATE INDEX AstBinding_label_idx IF NOT EXISTS ON AstBinding (label) NOTUNIQUE;

CREATE PROPERTY AstBinding.out IF NOT EXISTS LINK AstNode (NOTNULL);
CREATE PROPERTY AstBinding.in IF NOT EXISTS LINK AstNode (NOTNULL);

CREATE PROPERTY AstNode.out_AstBinding IF NOT EXISTS LINKLIST AstBinding;
CREATE PROPERTY AstNode.in_AstBinding IF NOT EXISTS LINKLIST AstBinding;
