CREATE CLASS DataFlowNode;
CREATE CLASS ProxyContainer;
 
CREATE PROPERTY DataFlowNode.type STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY DataFlowNode.name STRING (NOTNULL, DEFAULT "");
CREATE PROPERTY DataFlowNode.module LINK Module (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY DataFlowNode.astNode LINK AstNode;
CREATE PROPERTY DataFlowNode.relatedFields LINKSET DataFlowNode (NOTNULL, DEFAULT []);
CREATE PROPERTY DataFlowNode.readAccesses LINKSET DataFlowNode (NOTNULL, DEFAULT []);
CREATE PROPERTY DataFlowNode.writeAccesses LINKSET DataFlowNode (NOTNULL, DEFAULT []);
CREATE PROPERTY DataFlowNode.in_proxyShortcuts LINKSET DataFlowNode (NOTNULL, DEFAULT []);
CREATE PROPERTY DataFlowNode.out_proxyShortcuts LINKSET DataFlowNode (NOTNULL, DEFAULT []);
CREATE PROPERTY DataFlowNode.traced BOOLEAN (NOTNULL, DEFAULT FALSE);
 
CREATE PROPERTY ProxyContainer.type STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY ProxyContainer.module LINK Module (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY ProxyContainer.properties EMBEDDEDMAP STRING (NOTNULL, DEFAULT {});
CREATE PROPERTY ProxyContainer.fields LINKLIST DataFlowNode (NOTNULL, DEFAULT []);
CREATE PROPERTY ProxyContainer.statement LINK AstNode;