CREATE CLASS FieldInfo IF NOT EXISTS EXTENDS AdditionalInfo;
CREATE PROPERTY FieldInfo.ordinal IF NOT EXISTS INTEGER (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY FieldInfo.name  IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY FieldInfo.reference  IF NOT EXISTS STRING;
CREATE PROPERTY FieldInfo.properties  IF NOT EXISTS EMBEDDEDMAP STRING;

UPDATE TypeEnum set name="SCHEMA" UPSERT WHERE name="SCHEMA";
UPDATE TypeEnum set name="VIEW" UPSERT WHERE name="VIEW";
UPDATE TypeEnum set name="INDEX" UPSERT WHERE name="INDEX";
UPDATE TypeEnum set name="TRIGGER" UPSERT WHERE name="TRIGGER";

UPDATE ObjectType SET technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL"), typeLink=(SELECT FROM TypeEnum WHERE name="SCHEMA"), storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE"), originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM") UPSERT WHERE technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL") AND typeLink=(SELECT FROM TypeEnum WHERE name="SCHEMA") AND storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE") AND originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM");
UPDATE ObjectType SET technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL"), typeLink=(SELECT FROM TypeEnum WHERE name="TABLE"), storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE"), originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM") UPSERT WHERE technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL") AND typeLink=(SELECT FROM TypeEnum WHERE name="TABLE") AND storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE") AND originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM");
UPDATE ObjectType SET technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL"), typeLink=(SELECT FROM TypeEnum WHERE name="VIEW"), storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE"), originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM") UPSERT WHERE technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL") AND typeLink=(SELECT FROM TypeEnum WHERE name="VIEW") AND storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE") AND originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM");
UPDATE ObjectType SET technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL"), typeLink=(SELECT FROM TypeEnum WHERE name="INDEX"), storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE"), originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM") UPSERT WHERE technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL") AND typeLink=(SELECT FROM TypeEnum WHERE name="INDEX") AND storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE") AND originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM");
UPDATE ObjectType SET technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL"), typeLink=(SELECT FROM TypeEnum WHERE name="TRIGGER"), storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE"), originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM") UPSERT WHERE technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL") AND typeLink=(SELECT FROM TypeEnum WHERE name="TRIGGER") AND storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE") AND originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM");
UPDATE ObjectType SET technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL"), typeLink=(SELECT FROM TypeEnum WHERE name="STORED_PROCEDURE"), storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE"), originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM") UPSERT WHERE technologyLink=(SELECT FROM TechnologyEnum WHERE name="SQL") AND typeLink=(SELECT FROM TypeEnum WHERE name="STORED_PROCEDURE") AND storageLink=(SELECT FROM StorageEnum WHERE name="DATABASE") AND originLink=(SELECT FROM OriginEnum WHERE name="CUSTOM");
