#version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: kdarisi
      POSTGRES_PASSWORD: Kanya@9134
      POSTGRES_DB: StudentDatabase
    ports:
      - "5432:5432"
    networks:
      - sNetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/StudentDatabase
      SPRING_DATASOURCE_USERNAME: kdarisi
      SPRING_DATASOURCE_PASSWORD: Kanya@9134
    networks:
      - sNetwork

networks:
  sNetwork:
    driver: bridge
    
volumes:
  postgres_data:
    driver: local
