CREATE PROCEDURE ME10597B (
IN ARG_I_ID_PROGRAM VARCHAR(10),
IN ARG_I_ID VARCHAR(10),
IN ARG_I_NBR VARCHAR(10),
IN ARG_I_TS_REQUEST VARCHAR(10),
IN ARG_I_NBR_PHONE_FAX VARCHAR(10),
INOUT ARG_O_NBR_SQLCODE VARCHAR(10),
INOUT LKG001 VARCHAR(10)
)
NOT DETERMINISTIC
LANGUAGE JAVA
EXTERNAL NAME 'ME10094J:de.innowake.hq.ME10597B.run'
FENCED
THREADSAFE
PARAMETER STYLE JAVA