%INCLUDE %FROM %CDD 'CDD_REC.BEN_ABS2MC400'
%INCLUDE %FROM %CDD 'BEN_TEST'
%INCLUDE "DUMMY_FILE.inc" %FROM %LIBRARY "SYS$LIBRARY:BASIC_LIB.TLB"
%INCLUDE "DUMMY_FILE.rec" %FROM %LIBRARY "SYS$LIBRARY:BASIC_LIB.TLB"
%INCLUDE "MBRADDR.MAP" %FROM %LIBRARY "SYS$LIBRARY:BASIC_LIB.TLB"
CALL LIB$SPAWN ( '@COM:CLUR04.COM '+ Merge,,,,,,Completion_Stat)
OPEN "INPUT1.DAT" FOR INPUT AS FILE #4,                  &
	ORGANIZATION SEQUENTIAL FIXED,                 &
	RECORDSIZE 200,                                &
	MAP ABC,                                       &
	ALLOW MODIFY, ACCESS MODIFY
OPEN "INPUT2.DAT" FOR INPUT AS FILE #4,                  &
ORGANIZATION INDEXED FIXED,                 &
RECORDSIZE 200,                                &
MAP ABC,                                       &
ALLOW MODIFY, ACCESS MODIFY