CREATE PROCEDURE SYSPROC.SQLPGM
    (IN WSINDATE CHAR(8),
     OUT WSOUTDATE CHAR(8))
    EXTERNAL NAME SQLPGM LANGUAGE COBOL;
CREATE PROCEDURE SPROC1
    (IN WSINDATE CHAR(8),
     OUT WSOUTDATE CHAR(8))
    EXTERNAL NAME SQLPGM LANGUAGE COBOL;
CREATE PROCEDURE SYSPROC.SPROC2
    (IN WSINDATE CHAR(8),
     OUT WSOUTDATE CHAR(8))
    EXTERNAL NAME SQLPGM LANGUAGE COBOL;
CREATE PROCEDURE SYSPROC.SPROC3
    (IN WSINDATE CHAR(8),
     OUT WSOUTDATE CHAR(8))
    EXTERNAL NAME SQLPGM LANGUAGE COBOL;
