package innowake.mining.server.service.semanticsearch;


import java.beans.ConstructorProperties;
import java.util.Arrays;

/**
 * Represents semantic search result.
 */
public  class SemanticSearchResultPojo {

	private final String answer;
	private final SemanticSearchDocumentPojo[] documents;

	/**
	 * Constructs a new SemanticSearchResultPojo object
	 * @param answer the answer generated by the LLM
	 * @param documents the {@link SemanticSearchDocumentPojo documents} that match the semantic search request
	 */
	@ConstructorProperties({"answer","savedSearches","documents"})
	public SemanticSearchResultPojo(final String answer,
			final SemanticSearchDocumentPojo[] documents) {
		this.answer = answer;
		this.documents = documents;
	}

	/**
	 * @return the models answer
	 */
	@SuppressWarnings("unused") /* Required for JSON serialization */
	public String getAnswer() {
		return answer;
	}


	/**
	 * @return the documents used to generate the answer
	 */
	public SemanticSearchDocumentPojo[] getDocuments() {
		return documents;
	}



	@Override
	public String toString() {
		final StringBuilder sb = new StringBuilder("SemanticSearchResultPojo{");
		sb.append("answer='").append(answer).append('\'');
		sb.append(", documents=").append(Arrays.toString(documents));
		sb.append('}');
		return sb.toString();
	}
}
