000100 IDENTIFICATION DIVISION.                                         00010099
000200 PROGRAM-ID. WMIN7357                                             00020099
000800*  ***************************************************************00080099
000900*  * DESCRIPTION:                                                *00090099
001000*  *  Please note: Module descriptions are calculated only       *00120099
001100*  *               if they don't exist yet! Otherwise you first  *00121099
001200*  *               have to remove it, before calling Mining ->   *00122099
001200*  *               Analysis -> Identify Module Descriptions      *00123099
001300*  *                                                             *00120099
003100*  * REVISION-                                                   *00290099
003200*  *    DATE    PERSON     REASON                                *00300099
003300*  * 22-01-17   NPR        Minified test case to reproduce       *00280099
003800*  ***************************************************************00310099
003900*                                                                 00320099
004400 DATA 