REORG INDEX BQPFMIS1.IX_AE_1
REORG INDEX BQPFMIS1.IX_AE_2
REORG INDEX BQPFMIS1.IX_AE_3
REORG INDEX BQPFMIS1.IX_AE_4
REORG INDEX BQPFMIS1.IX_AE_5
REORG INDEX BQPFMIS1.IX_AE_6
REORG INDEX BQPFMIS1.IX_AE_7 PART 1
REORG INDEX BQPFMIS1.IX_AE_7 PART 2
REORG INDEX BQPFMIS1.IX_AE_7 PART 3
REORG INDEX BQPFMIS1.IX_AE_7 PART 4
REORG INDEX BQPFMIS1.IX_AE_7 PART 5
REORG INDEX BQPFMIS1.IX_AE_7 PART 6
REORG INDEX BQPFMIS1.IX_AE_7 PART 7
REORG INDEX BQPFMIS1.IX_AE_7 PART 8
REORG INDEX BQPFMIS1.IX_AE_7 PART 9
REORG INDEX BQPFMIS1.IX_AE_7 PART 10
REORG INDEX BQPFMIS1.IX_AE_7 PART 11
REORG INDEX BQPFMIS1.IX_AE_7 PART 12
REORG INDEX BQPFMIS1.IX_AE_7 PART 13
REORG INDEX BQPFMIS1.IX_AE_7 PART 14
REORG INDEX BQPFMIS1.IX_AE_7 PART 15
REORG INDEX BQPFMIS1.IX_AE_7 PART 16
REORG INDEX BQPFMIS1.IX_AE_7 PART 17
REORG INDEX BQPFMIS1.IX_AE_7 PART 18
REORG INDEX BQPFMIS1.IX_AE_7 PART 19
REORG INDEX BQPFMIS1.IX_AE_7 PART 20
REORG INDEX BQPFMIS1.IX_AE_8
REORG INDEX BQPFMIS1.IX_AE_9
