ALTER TABLE custom_enum ALTER COLUMN project SET NOT NULL;
ALTER TABLE dna_community ALTER COLUMN snapshot SET NOT NULL;
ALTER TABLE dna_snapshot ALTER COLUMN project SET NOT NULL;
ALTER TABLE functional_block ALTER COLUMN project SET NOT NULL;
ALTER TABLE source ALTER COLUMN project SET NOT NULL;

CREATE INDEX annotation_category_idx ON annotation USING btree (category);
CREATE INDEX annotation_module_idx ON annotation USING btree (module);
CREATE INDEX annotation_category_project_idx ON annotation_category USING btree (project, id);
CREATE INDEX data_dictionary_module_idx ON data_dictionary USING btree (module);
CREATE INDEX data_dictionary_annotations_annotation_idx ON data_dictionary_annotations USING btree (annotation);
CREATE INDEX dna_community_snapshot_idx ON dna_community USING btree (snapshot);
CREATE INDEX dna_community_modules_module_idx ON dna_community_modules USING btree (module);
CREATE INDEX dna_snapshot_project_idx ON dna_snapshot USING btree (project, id);
CREATE INDEX module_conditional_relationship_module_idx ON module_conditional_relationship USING btree (reached_from_module);
CREATE INDEX module_taxonomies_taxonomy_idx ON module_taxonomies USING btree (taxonomy);
CREATE INDEX reachability_data_intermediate_modules_module_idx ON reachability_data_intermediate_modules USING btree (intermediate_module);
CREATE INDEX source_project_idx ON source USING btree (project);
CREATE INDEX source_references_dst_idx ON source_references USING btree (dst);
CREATE INDEX taxonomy_type_idx ON taxonomy USING btree (type);
CREATE INDEX taxonomy_type_category_idx ON taxonomy_type USING btree (category);
