       IDENTIFICATION DIVISION.
       PROGRAM-ID.
           MODBC.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
   
       PROCEDURE DIVISION.

           DISPLAY "Inside Call"

           EXIT.
