%INCLUDE	'INC:BASICREC.REC'
%INCLUDE	'INC:BASICMAP.MAP'
%INCLUDE	'INC:BASICINC.INC'
%INCLUDE	'INC:Basicinc.INC'
%IF %VARIANT = 1%
	%THEN
	    %INCLUDE "INC:<Program_Name>.VER"
	%ELSE
	    DECLARE STRING CONSTANT Source_Version = "TEST"
	%END %IF