CREATE PROCEDURE SP_SUBSCRIBE(
    OUT RETURN_VALUE VARCHAR(80),
    IN PUBLICATION VARCHAR(8),
    IN ARTICLE VARCHAR(8),
    IN ISSUE SMALLINT,
    IN COUNT SMALLINT,
    IN OTHER VARCHAR(8)
)
    EXTERNAL NAME PRGPROC2 LANGUAGE COBOL;