ALTER TABLE "module" ALTER COLUMN "name" SET NOT NULL;
ALTER TABLE "module" ALTER COLUMN "technology" SET NOT NULL;
ALTER TABLE "module" ALTER COLUMN "type" SET NOT NULL;
ALTER TABLE "module" ALTER COLUMN "storage" SET NOT NULL;
ALTER TABLE "module" ALTER COLUMN "origin" SET NOT NULL;
ALTER TABLE "module" ALTER COLUMN "creator" SET NOT NULL;
ALTER TABLE "module" ALTER COLUMN "identified" SET NOT NULL;
ALTER TABLE "module" ALTER COLUMN "link_hash" SET NOT NULL;
