  CREATE TABLE PDBA.EMPLOYEE
  (
  EMPLOYEE_ID  INTEGER
   NOT NULL
 , EMPLOYEE_ORD  DECIMAL(2)
   NOT NULL
 , EMPLOYEE_TELECOM  DECIMAL(2)
   NOT NULL
 , EMPLOYEE_TELECOM_NAME  VARCHAR(30)
   NOT NULL
 , EMPLOYEE_ENT_CHNG  CHAR(8)
   NOT NULL
 , EMPLOYEE_MKNG_CHNG  CHAR(8)
   NOT NULL
 , EMPLOYEE_UPDATE  DATE
   NOT NULL
   WITH DEFAULT
 , EMPLOYEE_TM_UPDATE  TIME
   NOT NULL
   WITH DEFAULT
 , PRIMARY KEY ( EMPLOYEE_ID
  , EMPLOYEE_ORD
   )
  )
  IN DBT01.TS1
  ;
  CREATE TABLE student (
    id INT,
    name VARCHAR(50),
    age INT,
    percentage DECIMAL(10, 2)
);
  