/**
 * mining server REST API
 * This is the description of the mining server REST API endpoints.
 *
 * OpenAPI spec version: 99.9.99-TRUNK-MINING-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TokenInfo {
    bearerToken?: string;
    dateCreated?: Date;
    description?: string;
    id?: string;
    refreshToken?: string;
    subject?: string;
    username?: string;
}
