CREATE TABLE "PDBA"."EMPLOYEE"
  ( EMPLOYEE_ID  INTEGER   NOT NULL ,
    EMPLOYEE_ORD  DECIMAL(2)   NOT NULL ,
    EMPLOYEE_TELECOM  DECIMAL(2)   NOT NULL   )  IN DBT01.TS1  ;
 CREATE TABLE ABC.XYZ
  ( ID  INTEGER NOT NULL,
  	MOBILE  DECIMAL(2) NOT NULL
  )
  