UPDATE VENT_RULE A
-- This is a comment
SET RULE_XML = REPLACE(CAST(XMLSERIALIZE(RULE_XML
AS CLOB(9K) EXCLUDING XMLDECLARATION ) AS VARCHAR(9000)),
'VBS_Exrtcom',
'VOM_Rulecom')
WHERE VERSN_NO = :ED700-VERSN-NO
AND LST_UPDTD_USER_ID = :ED700-LST-UPDTD-USER-ID
AND LST_UPDTD_TS = :ED700-LST-UPDTD-TS 