DELETE VERTEX SavedSearch;
ALTER SEQUENCE SavedSearch_Sequence START 0 INCREMENT 1;
SELECT sequence('SavedSearch_Sequence').reset();

INSERT INTO SavedSearch SET usage="miningUi.annotationsTable", name="Business Rule Candidates", projectId=0, savedSearch='columns=Annotation.type&columns=Annotation.categoryName&columns=Annotation.reasons&columns=Module.name&columns=Annotation.sourceAttachment&columns=Annotation.state&columns=Module.technology&columns=Module.type&columns=Annotation.name&page=1&sort={content_module_name: ASC}&filter=[{"key":"type","value":["RULE"]},{"key":"categoryName","value":["Business Rule"]},{"key":"state","value":["CANDIDATE"]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.annotationsTable", name="Database Candidates", projectId=0, savedSearch='columns=Annotation.type&columns=Annotation.categoryName&columns=Module.name&columns=Annotation.sourceAttachment&columns=Annotation.state&columns=Module.technology&columns=Module.type&columns=Annotation.name&page=1&sort={content_module_name: ASC}&filter=[{"key":"type","value":["DATABASE"]},{"key":"state","value":["CANDIDATE"]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.annotationsTable", name="Dead Code", projectId=0, savedSearch='columns=Annotation.type&columns=Annotation.categoryName&columns=Module.name&columns=Annotation.sourceAttachment&columns=Module.technology&columns=Module.type&columns=Annotation.name&page=1&sort={content_module_name: ASC}&filter=[{"key":"type","value":["DEAD_CODE"]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.annotationsTable", name="Ungrouped Annotations", projectId=0, savedSearch='columns=Module.name&columns=Annotation.type&columns=Annotation.categoryName&columns=Annotation.state&columns=Annotation.name&columns=Annotation.sourceAttachment&columns=Annotation.englishTranslation&columns=AnnotationFunctionalGroup.name&columns=Annotation.updatedByUserName&page=1&&sort={content_module_name: ASC}&filter=[{"key":"functionalGroups.name","value":[""]}]', scope = (SELECT FROM ScopeEnum WHERE name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.dataDictionaryTable", name="Business Related DD Entries", projectId=0, savedSearch='columns=DataDictionaryEntry.isBusiness&columns=DataDictionaryEntry.dataElementName&columns=DataDictionaryEntry.format&columns=DataDictionaryEntry.length&columns=Module.name&columns=DataDictionaryEntry.description&columns=DataDictionaryEntry.created_by&page=1&sort={content_module_name: ASC}&filter=[{"key":"isBusiness","value":[true]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.dataDictionaryTable", name="Copybook Defined DD Entries", projectId=0, savedSearch='columns=DataDictionaryEntry.definedLocation&columns=DataDictionaryEntry.dataElementName&columns=DataDictionaryEntry.format&columns=DataDictionaryEntry.length&columns=Module.name&columns=DataDictionaryEntry.description&columns=DataDictionaryEntry.created_by&page=1&sort={content_module_name: ASC}&filter=[{"key":"definedLocation","value":["Copybook"]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.dataDictionaryTable", name="Not Referenced DD entries", projectId=0, savedSearch='columns=DataDictionaryEntry.isReferenced&columns=DataDictionaryEntry.dataElementName&columns=DataDictionaryEntry.format&columns=DataDictionaryEntry.length&columns=Module.name&columns=DataDictionaryEntry.description&columns=DataDictionaryEntry.created_by&page=1&sort={content_module_name: ASC}&filter=[{"key":"isReferenced","value":["false"]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.modulesTable", name="Missing Source Files", projectId=0, savedSearch='columns=Module.name&columns=Module.technology&columns=Module.type&columns=Module.identification&page=1&sort={content_name: ASC}&filter=[{"key":"identification","value":["MISSING"]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.modulesTable", name="", name="Modules with Errors", projectId=0, savedSearch='columns=Module.name&columns=Module.technology&columns=Module.type&columns=Module.errorCount&page=1&sort={content_name: ASC}&filter=[{"key":"errorCount","value":[{"operator":"gte","value":1}]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.modulesTable", name="No Taxonomies Assigned", projectId=0, savedSearch='columns=Module.name&columns=Module.technology&columns=Module.type&columns=Module.taxonomyCount&page=1&sort={content_name: ASC}&filter=[{"key":"taxonomyCount","value":[{"operator":"eq","value":0}]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.modulesTable", name="Not Referenced", projectId=0, savedSearch='columns=Module.name&columns=Module.technology&columns=Module.type&columns=Module.inboundDependencyCount&page=1&sort={content_name: ASC}&filter=[{"key":"inboundDependencyCount","value":[{"operator":"eq","value":0}]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.modulesTable", name="Requires Review", projectId=0, savedSearch='columns=Module.name&columns=Module.requiresReview&columns=Module.technology&columns=Module.type&page=1&sort={content_name: ASC}&filter=[{"key":"requiresReview","value":[true]}]', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
INSERT INTO SavedSearch SET usage="miningUi.modulesTable", name="Taxonomy Assignments", projectId=0, savedSearch='columns=Module.name&columns=Module.technology&columns=Module.type&columns=Module.taxonomyCount&page=1&sort={content_name: ASC}&filter=[{"key":"taxonomyCount","value":[{"operator":"gte","value":1}]}]', modifiers='ADD_ALL_TAXONOMIES', scope=(SELECT FROM ScopeEnum where name = 'GLOBAL');
