/** export the labelType constants to be used for extracting mappings based on technology, type and project. */
export enum LabelType  {
  TECHNOLOGY = 'TECHNOLOGY_LABELS',
  TYPE = 'TYPE_LABELS',
  PROJECT = 'PROJECT_LABELS',
  ERROR_KEY = 'ERROR_KEY_LABELS',
  ANNOTATION_METADATA_REASON = 'ANNOTATION_METADATA_REASON_LABELS',
  RELATIONSHIP = 'MODULE_DEPENDENCIES_RELATIONSHIP_LABELS',
  ANNOTATION_STATES = 'ANNOTATION_STATES',
  MODULE_TYPE = 'MODULE_TYPE_LABELS'
};
