$ ON ERROR THEN GOTO ERROR_CONDITION
$ INITIALIZATION:
$       RUN_STATUS = "INITIALIZATION"
$       JOB_NAME :== "ENID100"
$       @COM:INITIALIZATION
$       @COM:OPKD03A.COM
$       MAIL_LIST  = "@CLM_TEAM"
$!
$!   
$!
$ DEF    UNUSED_LOGICAL         CORRECT1
$ DEF    DENIAL_LETTER_TBL_IND  PRDIND_LTR_DISK:[DEN_LTRS]DENLTBL.TBL
$ def    ack_file_ftp           'ACKNOWLEDGMENT_FILE
$ DEF    CLM_CON_EXT_CSP_FILE   CLMWORK:CLM_CON_EXT_CSP_PPO.SEQ
$ DEF    CLM_CON_XML_CSP_FILE   CLM_RPT:CLM_CON_XML_CSP_PPO.PRT
$ DEF    SYS$OUTPUT             NL:
$ DEF    CMK_FILE_TMP           'Output_File_Name_Srt'
$ DEFINE BEN_REPORT_ERR         "ERR"
$ DEFINE VND_FTL_MESSAGE        CLMWORK:CLM_VND_BUD_01_MSG_'P1'.TXT
$ DEfINE ACS_BATCH_LOG_FILE     MACWORK:ACS_BATCH_LOG_FILE.ISM		!mod #30
$ DEFINE XML_DATA_FILE          CSP_WORK:CSP_EOB_DATA.XML
$ DEFINE ENCFHE09_COPAY_OUT -
                                ENC_REPORTS_INTERNAL:ENPD_COPAY_'ICFROZEN_DATE'_TMP.PRT
$        WRITE FTP_COM "$  DEFINE EMAIL_FILENAME WORK:OVERRIDE_FTP_COM_FILE.doc"
$       ENIP100_RUN :== "$EXE:ENIP100.EXE ''PGM_MODE'"
$       ENIP100_RUN 
$       NOT_PRESENT_RUN :== $EXE:NOT_PRESENT ''PGM_MODE'
$       NOT_PRESENT_RUN 