
   DEAD: PROC;
   PUT SKIP LIST(PARAM1);
   PUT SKIP LIST(PARAM2);
   PUT SKIP LIST(PARAM1);
   PUT SKIP LIST(PARAM2);
   PUT SKIP LIST(PARAM1);
   PUT SKIP LIST(PARAM2);
   PUT SKIP LIST(PARAM1);
   PUT SKIP LIST(PARAM2);
   PUT SKIP LIST(PARAM1);
   PUT SKIP LIST(PARAM2);
   PUT SKIP LIST(PARAM1);
   PUT SKIP LIST(PARAM2);
   PUT SKIP LIST(PARAM1);
   PUT SKIP LIST(PARAM2);
 