	       SUBTRACT WS-NUM1 WS-NUM2 FROM WS-NUM3 WS-NUM4.
           SUBTRACT WS-NUMA WS-NUMB WS-NUMC FROM WS-NUMD GIVING WS-NUME.
           COMPUTE ABCD = ABC + AB
           ADD 3 TO WS-NUM4
           COMPUTE ABCD = WS-NUM3 + AB
           
           GOBACK.
