	This program,  and all the routines referenced  herein,   are the
	proprietary properties and trade secrets of XXXXXXXXXX.
	Except as provided for by license agreement,   this program
	shall not  be  duplicated,  used  or  disclosed  without  written
	consent, signed by an officer of XXXXXXXXXX.
	SYSTEM:		XXX System
	PROGRAM:	XXXXXXXXXXXXXXXX.BAS
	OVERVIEW:	Reporting of the file Contents of XXXXXXXXXXXXXXXXXXXXXXXX.
                      (File Dump of XXXXXXXXXXXXXXXXX).
			Stand-Alone Application, No Online Dependency
      COMMAND FILE:   XXXXXXXXXXXXXXXXXXXX
	DATE:		XXXXXXXXX
	AUTHOR:  	XXXXXXXXXXX
      WFILE:  	XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      WDESC:  	XXXXXXXXX File Dump File Listing
      RFILE: 		XXXXXXXXXXXXXXXXXXXXXXXX (XXXXXXXXXXXXX)
      RDESC:  	XXXXX Benefit Translation File