       SYSTEM:  XXXXXXXXXXXXX                                                
       PROGRAM: XXXXXXXXXXXXXXXXXXXXXX                                       
       TITLE:   XXXXXXXXXXXXXXXXXXXXXX                                       
       DATE:    XXXXXXXXXXX                                                  
       AUTHOR:  XXXXXXXXXXXXXXXXXXXXXXXX                                     
 OVERVIEW:                                                                   
      Inserting corresponding parent record for the child record in          
      XXXXXXXXX file                                                         
 MOD #      DD-MMM-CCYY   USER NAME(VMS ID)               ISR#
 INITIAL    XXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXX
 CREATION