
  This source code, and all the routines referenced herein, are the
  proprietary properties and trade secrets of XXXXXX XXX, INC. Except as
  provided for by license agreement, this source code shall not be
  duplicated, used or disclosed without written consent, signed by an
  officer of XXXXXX XXX, INC.

  SYSTEM:   XXXXXXXXXX
  PROGRAM:  XXXXXXXXXXXXXX
  TITLE:    XXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXX.
  DATE:     XXXXXXXXXXX
  AUTHOR:   XXXXXXX XXXXXXXXXXXX XXXXX
  OVERVIEW: This Program is used to XXXX XXXXXXX XX XXXXXXXXXXXXX XXXX.

=====================================================================================================

Modification History:

   MOD#   DD-MMM-CCYY    NAME (VMS ID)           DESCRIPTION

 INITIAL  XXXXXXXXXXX  XXXXXXX XXXXXXXXXXXX XXXXX  XXXXXXXXX
 CREATION                                          XXXXXXXXX XXXX XXXXXXXXX
                                                   XXXXX XXXXXXXXXXXX

=====================================================================================================