spring:
  application:
   name: spring-boot-config

app:
  name: My App
  desc: welcome to ${app.name}

my:
  greeting: "Hello world!!"
  list:
   values: one,two,three

dbvalues: "{connectionString: 'http://-----.com', userName: 'user', password: 'pass'}"
db:
  connection: {connectionString: 'http://-----.com', userName: 'user', password: 'pass'}
  host: "127.0.0.test"
  port: 2400

management.endpoints.web.exposure.include: "*"
#spring.profiles.active: test

# spring.cloud.config.uri: http://localhost:8081/
spring.config.import: configserver:http://localhost:8081/

