server:
  port: 8081
spring:
  codec:
    max-in-memory-size: 1GB
service-discovery:
  group-id: innowake.products.mining.mining-opensearch
mining-opensearch:
  opensearch:
    url: https://localhost:9200/
    username: admin
    password: admin
  mining:
    url: http://localhost:8080/api/
    # ---- place your keycloak (or other forms of authenitcation) token here ----
    # ---- leave empty if authentication is not active ---- 
    access-token: 5COgpjv7HdUiRQrj0LwEsyiJnhE
    is-offline-token: true
  indexes:
    moduletable:
      queryName: modules
      rootType: PAGE_Module
      usage: miningUi.modulesTable
      id: content.id
    sourcecode:
      queryName: modules
      rootType: PAGE_Module
      datapoints:
        - path: content.sourceAttachmentLink.content
          type: text
        - path: content.id
          type: long
      id: content.id
    annotationtable:
      queryName: annotations
      rootType: PAGE_Annotation
      usage: miningUi.annotationsTable
      id: content.id
  performance:
    index-threads: 16
    
# logging.level.reactor.netty.http.client.HttpClient: DEBUG