spring:
    datasource:
        enabled: false
    flyway:
        enabled: false
mining:
    taxonomies:
        fetchModulePartitionSize: 1
    user:
        username: admin
        password: Worx2000
        token: 5COgpjv7HdUiRQrj0LwEsyiJnhE
