debug: true # Enable debug logs.
trace: false # Enable trace logs.
logging:
    level:
        org.springframework.aop.interceptor.PerformanceMonitorInterceptor: TRACE
        org.apache.tomcat.util.net.NioEndpoint: ERROR
        innowake.mining.server.controller: TRACE
        innowake.mining.data: TRACE
cors:
    allowed-origins: http://localhost:4200,http://127.0.0.1:4200,http://localhost:8180,http://127.0.0.1:8180,http://localhost:8080,http://127.0.0.1:8080
dbcutter-db-postgres:
    enabled: false

mining:
    user:
        username: admin
        password: Worx2000
        token: 5COgpjv7HdUiRQrj0LwEsyiJnhE