CREATE CLASS ModuleFilter IF NOT EXISTS;
CREATE PROPERTY ModuleFilter.moduleId IF NOT EXISTS LONG;
CREATE PROPERTY ModuleFilter.names IF NOT EXISTS EMBEDDEDSET (NOTNULL, DEFAULT []);
CREATE PROPERTY ModuleFilter.types IF NOT EXISTS EMBEDDEDSET (NOTNULL, DEFAULT []);
CREATE PROPERTY ModuleFilter.paths IF NOT EXISTS EMBEDDEDSET (NOTNULL, DEFAULT []);
CREATE PROPERTY ModuleFilter.pathPatterns IF NOT EXISTS EMBEDDEDSET (NOTNULL, DEFAULT []);
CREATE PROPERTY ModuleFilter.containedIn IF NOT EXISTS EMBEDDED ModuleFilter;

CREATE CLASS DependencyDefinition IF NOT EXISTS;
CREATE PROPERTY DependencyDefinition.moduleLink IF NOT EXISTS LINK Module (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY DependencyDefinition.moduleFilter IF NOT EXISTS EMBEDDED ModuleFilter (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY DependencyDefinition.resolutionFlags IF NOT EXISTS EMBEDDEDSET (NOTNULL, DEFAULT []);
CREATE PROPERTY DependencyDefinition.location IF NOT EXISTS EMBEDDED ModuleLocation;
CREATE PROPERTY DependencyDefinition.relationshipType IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY DependencyDefinition.bindingType IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY DependencyDefinition.attributes IF NOT EXISTS EMBEDDEDMAP (NOTNULL, DEFAULT {});
CREATE PROPERTY DependencyDefinition.resolved IF NOT EXISTS BOOLEAN (DEFAULT false);

