CREATE CLASS DataFlowError IF NOT EXISTS;
CREATE PROPERTY DataFlowError.severity IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY DataFlowError.text IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);

CREATE PROPERTY DataFlowNode.errors IF NOT EXISTS EMBEDDEDSET DataFlowError (NOTNULL, MANDATORY TRUE, DEFAULT []);