CREATE CLASS EdgeReference IF NOT EXISTS;
CREATE PROPERTY EdgeReference.jobId IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY EdgeReference.moduleRid IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY EdgeReference.referenceRid IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY EdgeReference.edgeName IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE PROPERTY EdgeReference.direction IF NOT EXISTS STRING (NOTNULL, MANDATORY TRUE);
CREATE INDEX EdgeReference.jobId IF NOT EXISTS ON EdgeReference (jobId) NOTUNIQUE;
CREATE INDEX EdgeReference.jobId_moduleRid IF NOT EXISTS ON EdgeReference (jobId, moduleRid) NOTUNIQUE;
