--################################################################################################
-- Updated Global Saved Search for Modules, Annotation and Data Dictionary
--################################################################################################


update SavedSearch SET name="Missing Source Files", usage="miningUi.modulesTable", projectLink=(SELECT FROM Project WHERE id=0), savedSearch='columns=Module.name&columns=ObjectType.technologyLink&columns=ObjectType.typeLink&columns=Module.identificationLink&page=1&sort=name.toLowerCase();ASC&filter=[{"key":"identificationLink","value":["MISSING"]}]' UPSERT WHERE name="Missing Source Files" AND projectLink.id=0;
update SavedSearch SET name="Not Referenced", usage="miningUi.modulesTable", projectLink=(SELECT FROM Project WHERE id=0), savedSearch='columns=Module.name&columns=ObjectType.technologyLink&columns=ObjectType.typeLink&columns=Module.inboundDependencyCount&page=1&sort=name.toLowerCase();ASC&filter=[{"key":"inboundDependencyCount","value":[{"operator":"eq","value":0}]}]' UPSERT WHERE name="Not Referenced" AND projectLink.id=0;
update SavedSearch SET name="No Taxonomies Assigned", usage="miningUi.modulesTable", projectLink=(SELECT FROM Project WHERE id=0), savedSearch='columns=Module.name&columns=ObjectType.technologyLink&columns=ObjectType.typeLink&columns=Module.taxonomyCount&page=1&sort=name.toLowerCase();ASC&filter=[{"key":"taxonomyCount","value":[{"operator":"eq","value":0}]}]' UPSERT WHERE name="No Taxonomies Assigned" AND projectLink.id=0;
update SavedSearch SET name="Taxonomy Assignments", usage="miningUi.modulesTable", modifiers='ADD_ALL_TAXONOMIES', projectLink=(SELECT FROM Project WHERE id=0), savedSearch='columns=Module.name&columns=ObjectType.technologyLink&columns=ObjectType.typeLink&columns=Module.toLowerCase().taxonomyCount&page=1&sort=name.toLowerCase();ASC&filter=[{"key":"taxonomyCount","value":[{"operator":"gte","value":1}]}]' UPSERT WHERE name="Taxonomy Assignments" AND projectLink.id=0;
update SavedSearch SET savedSearch='columns=Annotation.typeLink&columns=AnnotationCategory.name&columns=Module.name&columns=Annotation.sourceAttachment&columns=Annotation.stateLink&columns=ObjectType.technologyLink&columns=ObjectType.typeLink&columns=Annotation.name&page=1&sort=in_HasAnnotation.out.name.toLowerCase();ASC&filter=[{"key":"typeLink","value":["RULE"]},{"key":"categoryLink.name","value":["Business Rule"]},{"key":"stateLink","value":["CANDIDATE"]}]' WHERE name="Business Rule Candidates" AND projectLink.id=0;
update SavedSearch SET savedSearch='columns=Annotation.typeLink&columns=AnnotationCategory.name&columns=Module.name&columns=Annotation.sourceAttachment&columns=Annotation.stateLink&columns=ObjectType.technologyLink&columns=ObjectType.typeLink&columns=Annotation.name&page=1&sort=in_HasAnnotation.out.name.toLowerCase();ASC&filter=[{"key":"typeLink","value":["DATABASE"]},{"key":"stateLink","value":["CANDIDATE"]}]' WHERE name="Database Candidates" AND projectLink.id=0;
update SavedSearch SET savedSearch='columns=Annotation.typeLink&columns=AnnotationCategory.name&columns=Module.name&columns=Annotation.sourceAttachment&columns=ObjectType.technologyLink&columns=ObjectType.typeLink&columns=Annotation.name&page=1&sort=in_HasAnnotation.out.name.toLowerCase();ASC&filter=[{"key":"typeLink","value":["DEAD_CODE"]}]' WHERE name="Dead Code" AND projectLink.id=0;
update SavedSearch SET savedSearch='columns=Module.name&columns=Module.requiresReview&columns=ObjectType.technologyLink&columns=ObjectType.typeLink&page=1&sort=name.toLowerCase();ASC&filter=[{"key":"requiresReview","value":[true]}]' WHERE name="Requires Review" AND projectLink.id=0;
update SavedSearch SET savedSearch='columns=DataDictionaryEntry.isBusiness&columns=DataDictionaryEntry.dataElementName&columns=DataDictionaryEntry.format&columns=DataDictionaryEntry.length&columns=Module.name&columns=DataDictionaryEntry.description&columns=DataDictionaryEntry.createdByUserId&page=1&sort=in_HasDataDictionaryEntry.out.name.toLowerCase();ASC&filter=[{"key":"isBusiness","value":[true]}]' WHERE name="Business Related DD Entries" AND projectLink.id=0;
update SavedSearch SET savedSearch='columns=DataDictionaryEntry.definedLocation&columns=DataDictionaryEntry.dataElementName&columns=DataDictionaryEntry.format&columns=DataDictionaryEntry.length&columns=Module.name&columns=DataDictionaryEntry.description&columns=DataDictionaryEntry.createdByUserId&page=1&sort=in_HasDataDictionaryEntry.out.name.toLowerCase();ASC&filter=[{"key":"definedLocation","value":["Copybook"]}]' WHERE name="Copybook Defined DD Entries" AND projectLink.id=0;
update SavedSearch SET savedSearch='columns=DataDictionaryEntry.isReferenced&columns=DataDictionaryEntry.dataElementName&columns=DataDictionaryEntry.format&columns=DataDictionaryEntry.length&columns=Module.name&columns=DataDictionaryEntry.description&columns=DataDictionaryEntry.createdByUserId&page=1&sort=in_HasDataDictionaryEntry.out.name.toLowerCase();ASC&filter=[{"key":"isReferenced","value":["false"]}]' WHERE name="Not Referenced DD entries" AND projectLink.id=0;
