$ SET NOVERIFY        
$ SET PREFIX  "(!5%T) "
$ ON ERROR THEN GOTO ERROR_EXIT
$ INITIALIZATION:

$ @COM:INITIALIZATION
$ SET TERM/NOLINE
$ SET NOCONTROL=Y
$ !SAVE_DIR = F$ENVIRONMENT("DEFAULT")
$ DEFINE/NOLOG SYS$INPUT SYS$COMMAND
$ ASSIGN/NOLOG SYS$COMMAND SYS$INPUT
$ RUN EXE:BEN_BASIC_01        
$ !SET DEFAULT 'Save_Dir'
$ SET TERM/LINE
$ SET CONTROL=Y
$ EXIT

$ WRAP_UP:
$   @COM:TERMINATION
$ EXIT
$ Error_Exit:
$ Exit 44		 Exit with "Abort" message
